name: Buat Aplikasi APK Winamp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Ambil Kode Program
      uses: actions/checkout@v4

    - name: Siapkan Lingkungan Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Siapkan Java JDK Mandiri
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Instal Alat Perakitan Linux
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev lldd scons ccze
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Cetak File APK Final
      run: |
        # Menjalankan perakitan dan menyimpan laporan ke file log jika terjadi crash
        yes y | buildozer --allow-root -v android debug > buildozer_output.log 2>&1

    - name: Simpan Laporan Log Error jika Gagal
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Laporan-Log-Error-Perakitan
        path: |
          buildozer_output.log
          bin/*.apk
