name: Buat Aplikasi APK Winamp

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kode Program
      uses: actions/checkout@v4

    - name: Siapkan Lingkungan Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instal Alat Perakitan SDK Android
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev lldd scons texlive-extra-utils openjdk-17-jdk
        pip install buildozer cython virtualenv

    - name: Setujui Lisensi Android Google Otomatis
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg

    - name: Cetak File APK Final
      run: |
        # PERBAIKAN UTAMA: Menambahkan perintah auto-yes dan bypass root untuk Linux GitHub
        yes y | buildozer --allow-root -v android debug

    - name: Simpan File APK Siap Unduh
      uses: actions/upload-artifact@v4
      with:
        name: Aplikasi-Winamp-Mobile-Anda
        path: bin/*.apk
